// ui/src/app/components/entity/entity-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { EntityService } from '../../services/entity.service';
import { MetadataService, EntityMetadata } from '../../services/metadata.service';
import { FormGeneratorService, FormMode, VIEW, CREATE, EDIT } from '../../services/form-generator.service';
import { CommonModule } from '@angular/common';
import { RestService } from '../../services/rest.service';

@Component({
  selector: 'app-entity-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  providers: [RestService],
  template: `
    <div class="container mt-4">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2>{{ mode }} {{ entityType | titlecase }}</h2>
        <button class="btn btn-secondary" (click)="goBack()">Back</button>
      </div>
      
      <div *ngIf="loading" class="text-center">
        <p>Loading...</p>
      </div>
      
      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>
      
      <div *ngIf="!loading && !error && entityForm">
        <form [formGroup]="entityForm" (ngSubmit)="onSubmit()">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <ng-container *ngFor="let fieldName of sortedFields">
                  <div class="col-md-6 mb-3">
                    <label [for]="fieldName" class="form-label">
                      {{ getFieldDisplayName(fieldName) }}
                      <span *ngIf="isFieldRequired(fieldName)" class="text-danger">*</span>
                    </label>
                    
                    <!-- All form controls using formControlName automatically handle disabled state -->
                    <!-- Disabled controls will have their values populated by populateFormValues -->
                    <!-- So we can use the same controls for all states (view/edit/create) -->
                    <ng-container [ngSwitch]="formGenerator.getFieldWidget(entityType, fieldName, mode)">
                      
                      <!-- Select dropdown -->
                      <select *ngSwitchCase="'select'" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-select"
                        [class.is-invalid]="isFieldInvalid(fieldName)">
                        <option value="">Select {{ getFieldDisplayName(fieldName) }}</option>
                        <option *ngFor="let option of getFieldOptions(fieldName)" [value]="option">
                          {{ option }}
                        </option>
                      </select>
                      
                      <!-- Checkbox -->
                      <div *ngSwitchCase="'checkbox'" class="form-check mt-2">
                        <input type="checkbox" 
                          [id]="fieldName" 
                          [formControlName]="fieldName" 
                          class="form-check-input"
                          [class.is-invalid]="isFieldInvalid(fieldName)">
                        <label [for]="fieldName" class="form-check-label">
                          {{ getFieldDisplayName(fieldName) }}
                        </label>
                      </div>
                      
                      <!-- Textarea -->
                      <textarea *ngSwitchCase="'textarea'" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)"
                        rows="3"></textarea>
                      
                      <!-- Date input -->
                      <input *ngSwitchCase="'date'" 
                        type="datetime-local" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)">
                      
                      <!-- Password input -->
                      <input *ngSwitchCase="'password'" 
                        type="password" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)">
                        
                      <!-- Email input -->
                      <input *ngSwitchCase="'email'" 
                        type="email" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)">
                        
                      <!-- Reference input (for ObjectId fields) -->
                      <input *ngSwitchCase="'reference'" 
                        type="text" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)"
                        placeholder="Select or enter ID">
                      
                      <!-- JSON input -->
                      <textarea *ngSwitchCase="'json'" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)"
                        rows="3"
                        placeholder="{ }"></textarea>
                      
                      <!-- Array input -->
                      <textarea *ngSwitchCase="'array'" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)"
                        rows="3"
                        placeholder="[]"></textarea>
                      
                      <!-- Default text input -->
                      <input *ngSwitchDefault 
                        type="text" 
                        [id]="fieldName" 
                        [formControlName]="fieldName" 
                        class="form-control"
                        [class.is-invalid]="isFieldInvalid(fieldName)">
                    </ng-container>
                    
                    <!-- Validation error messages -->
                    <div *ngIf="isFieldInvalid(fieldName)" class="invalid-feedback">
                      <div *ngIf="entityForm && entityForm.get(fieldName)?.errors?.['required']">
                        {{ getFieldDisplayName(fieldName) }} is required.
                      </div>
                      <div *ngIf="entityForm && entityForm.get(fieldName)?.errors?.['minlength']">
                        {{ getFieldDisplayName(fieldName) }} must be at least 
                        {{ entityForm.get(fieldName)?.errors?.['minlength']?.requiredLength }} characters.
                      </div>
                      <div *ngIf="entityForm && entityForm.get(fieldName)?.errors?.['maxlength']">
                        {{ getFieldDisplayName(fieldName) }} cannot exceed 
                        {{ entityForm.get(fieldName)?.errors?.['maxlength']?.requiredLength }} characters.
                      </div>
                      <div *ngIf="entityForm && entityForm.get(fieldName)?.errors?.['pattern']">
                        {{ getFieldDisplayName(fieldName) }} has an invalid format.
                      </div>
                      <div *ngIf="entityForm && entityForm.get(fieldName)?.errors?.['min']">
                        {{ getFieldDisplayName(fieldName) }} must be at least 
                        {{ entityForm.get(fieldName)?.errors?.['min']?.min }}.
                      </div>
                      <div *ngIf="entityForm && entityForm.get(fieldName)?.errors?.['max']">
                        {{ getFieldDisplayName(fieldName) }} cannot exceed 
                        {{ entityForm.get(fieldName)?.errors?.['max']?.max }}.
                      </div>
                    </div>
                  </div>
                </ng-container>
              </div>
            </div>

          <div class="card-footer d-flex justify-content-between">
            <!-- Left side (for view mode) -->
            <div>
              <ng-container *ngIf="isViewMode()">
                <div *ngIf="entityService.canUpdate(entityType)">
                  <button type="button" class="btn btn-primary me-2" (click)="goToEdit()">Edit</button>
                </div>
                <div *ngIf="entityService.canDelete(entityType)">
                  <button type="button" class="btn btn-danger" (click)="restService.deleteEntity(entityType, entityId)">Delete</button>
                </div>
              </ng-container>
            </div>

            <!-- Right side (for edit/create mode) -->
            <div>
              <ng-container *ngIf="!isViewMode()">
                <button type="submit" class="btn btn-primary" [disabled]="entityForm && entityForm.invalid || submitting">
                  {{ submitting ? 'Saving...' : 'Submit' }}
                </button>
                <button type="button" class="btn btn-secondary ms-2" (click)="goBack()">Cancel</button>
              </ng-container>
            </div>
          </div>
          </div>
        </form>
      </div>
    </div>
  `,
  styles: [`
    .container { max-width: 1000px; }
    
    /* Style for disabled (read-only) form controls */
    .form-control:disabled,
    .form-select:disabled,
    .form-check-input:disabled {
      background-color: #f8f9fa; /* Light gray background */
      color: #212529; /* Dark text for readability */
      opacity: 1; /* Full opacity for better readability */
      cursor: default;
      border: 1px solid #dee2e6;
    }
  `]
})

export class EntityFormComponent implements OnInit {
  readonly ID_FIELD = '_id'; // Changed from private to public

  entityType: string = '';
  entityId: string = '';
  
  data: any[] = [];
  entityMetadata: EntityMetadata | null = null;
  entityForm: FormGroup | null = null;
  sortedFields: string[] = [];
  entity: any = null;
  
  loading: boolean = true;
  submitting: boolean = false;
  error: string = '';

  mode: FormMode = VIEW;
  
  constructor(
    private route: ActivatedRoute,
    private router: Router,
    public entityService: EntityService,
    private metadataService: MetadataService,
    public formGenerator: FormGeneratorService,
    public restService: RestService
  ) {}
  
  // Helper methods for template conditions
  isViewMode(): boolean {
    return this.mode === VIEW;
  }
  
  isEditMode(): boolean {
    return this.mode === EDIT;
  }
  
  isCreateMode(): boolean {
    return this.mode === CREATE;
  }

  ngOnInit(): void {
    // Simplified initialization
    this.route.params.subscribe(params => {
      this.entityType = params['entityType'];
      this.entityId = params['id'];
      
      const url = this.router.url;
      
      if (url.includes('/create')) {
        this.mode = CREATE;
      } else if (url.includes('/edit')) {
        this.mode = EDIT;
      } else {
        this.mode = VIEW;
      }
      
      this.loadEntity();
    });
  }

  loadEntity(): void {
    this.loading = true;
    this.error = '';
    
    // Generate the form first (same for all modes)
    const result = this.formGenerator.generateEntityForm(this.entityType, this.mode);
    this.entityForm = result.form;
    this.sortedFields = result.displayFields;
    
    // For create mode, just populate with defaults and we're done
    if (this.isCreateMode()) {
      this.populateFormValues();
      this.loading = false;
      return;
    }
    
    // For edit/view mode, fetch the data first, then populate
    this.restService.getEntity(this.entityType, this.entityId).subscribe({
      next: (response) => {
        this.entity = response.data || response;
        
        if (!this.entity) {
          this.error = 'No entity data returned from the server.';
          this.loading = false;
          return;
        }
        
        // Populate form with entity data for edit/view mode
        this.populateFormValues(this.entity);
        this.loading = false;
      },
      error: (err) => {
        console.error('Error loading entity:', err);
        this.error = 'Failed to load entity data. Please try again later.';
        this.loading = false;
      }
    });
  }

  // initForm method removed - logic moved directly into loadMetadataForCreate and loadEntityForEdit

  getFieldDisplayName(fieldName: string): string {
    if (fieldName === this.ID_FIELD) return 'ID';
    const fieldMeta = this.metadataService.getFieldMetadata(this.entityType, fieldName);
    return fieldMeta?.ui?.displayName || fieldName;
  }



  getFieldOptions(fieldName: string): string[] {
    const fieldMeta = this.metadataService.getFieldMetadata(this.entityType, fieldName);
    if (!fieldMeta || !fieldMeta.enum || !fieldMeta.enum.values) return [];
    
    return fieldMeta.enum.values;
  }

  isFieldRequired(fieldName: string): boolean {
    if (fieldName === this.ID_FIELD) return true;
    
    const fieldMeta = this.metadataService.getFieldMetadata(this.entityType, fieldName);
    if (!fieldMeta) return false;
    
    // Field required property is at the root level, not in the UI object
    return fieldMeta.required || false;
  }

  isFieldInvalid(fieldName: string): boolean {
    if (!this.entityForm) return false;
    const control = this.entityForm.get(fieldName);
    return !!control && control.invalid && (control.dirty || control.touched);
  }
  
  isFieldReadOnly(fieldName: string): boolean {
    if (!this.entityForm) return false;
    const control = this.entityForm.get(fieldName);
    return control?.disabled || false;
  }
  
  
  /**
   * Populates form values based on mode and entity data
   * @param entityData Optional entity data for edit/view modes
   */
  populateFormValues(entityData?: any): void {
    if (!this.entityForm || !this.sortedFields.length) return;
    
    // Process each field
    for (const fieldName of this.sortedFields) {
      const control = this.entityForm.get(fieldName);
      if (!control) continue;
      
      // Get field metadata
      const fieldMeta = this.metadataService.getFieldMetadata(this.entityType, fieldName);
      
      // Get the value based on mode
      let value;
      
      if (this.isCreateMode()) {
        // Use default values for create mode
        value = this.getDefaultValue(fieldMeta);
        
        // Handle special types that need specific default values
        if (fieldMeta?.type === 'ISODate' && (fieldMeta?.autoGenerate || fieldMeta?.autoUpdate)) {
          // For auto-generate/update fields in create mode, use current date
          value = new Date().toISOString().substring(0, 16); // Format for datetime-local
        }
      } else {
        // Use entity data for edit/view modes
        value = entityData?.[fieldName];
        
        // Handle ISODate fields specially
        if (fieldMeta?.type === 'ISODate') {
          if (!value) {
            // For empty dates, ensure we display them properly as completely empty
            value = null; // Use null instead of empty string for date fields
          } else if (value) {
            try {
              // Format valid date strings
              if (typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T/)) {
                // For input[type=datetime-local], format as YYYY-MM-DDThh:mm
                const date = new Date(value);
                value = date.toISOString().substring(0, 16); // Format for datetime-local input
              }
            } catch (e) {
              console.error('Error formatting date:', e);
            }
          }
          
          // For auto-update fields in edit mode, use current date
          if (this.isEditMode() && fieldMeta?.autoUpdate) {
            value = new Date().toISOString().substring(0, 16);
          }
        }
      }
      
      // Set value (disabled state is already handled by form generator)
      control.setValue(value);
    }
  }

  private getDefaultValue(fieldMeta: any): any {
    const type = fieldMeta.type;
    const widget = fieldMeta.ui?.widget || fieldMeta.widget;
    const enumValues = fieldMeta.enum?.values;
    const required = fieldMeta.required;
    
    switch (type) {
      case 'String':
        // For select fields with enum values, default to first value if required
        if (widget === 'select' && enumValues?.length > 0 && required) {
          return enumValues[0];
        }
        return '';
      case 'Number':
      case 'Integer':
        return required ? 0 : null;
      case 'Boolean':
        return false;
      case 'Array':
      case 'Array[String]':
        return [];
      case 'JSON':
        return {};
      case 'ISODate':
        // Always set current date for autoGenerate and autoUpdate fields
        if (fieldMeta.autoGenerate || fieldMeta.autoUpdate) {
          const now = new Date().toISOString();
          return now;
        }
        return null;
      case 'ObjectId':
        return '';
      default:
        return null;
    }
  }

  onSubmit(): void {
    if (!this.entityForm || this.entityForm.invalid) return;
    
    // For view mode, go to edit instead of submitting
    if (this.isViewMode()) {
      this.goToEdit();
      return;
    }
    
    this.submitting = true;
    let formData = this.entityForm.value;
    
    // Process the form data before sending it to the API
    formData = this.processFormData(formData);
    
    if (this.isEditMode()) {
      this.updateEntity(formData);
    } else if (this.isCreateMode()) {
      this.createEntity(formData);
    }
  }
  
  // Process form data before submitting to the API
  processFormData(formData: any): any {
    // Clone the data to avoid modifying the form values directly
    const processedData = { ...formData };
    
    try {
      if (!this.entityForm) return processedData;
      
      // Process all form controls directly (including disabled fields)
      for (const fieldName in this.entityForm.controls) {
        const control = this.entityForm.controls[fieldName];
        const fieldMeta = this.metadataService.getFieldMetadata(this.entityType, fieldName);
        
        if (control.disabled) {
          // Add disabled field values to the processed data (they're excluded from formData by default)
          const value = control.value;
          if (value !== undefined && value !== null) {
            processedData[fieldName] = value;
          }
        }
        
        // Special handling for specific field types
        if (fieldMeta && fieldMeta.type === 'ISODate') {
          const currentTime = new Date().toISOString();
          
          // For create operations, handle autoGenerate fields
          if (this.isCreateMode() && fieldMeta.autoGenerate) {
            processedData[fieldName] = currentTime;
          }
          
          // For both create and edit operations, always update autoUpdate fields
          if (fieldMeta.autoUpdate) {
            processedData[fieldName] = currentTime;
          }
        }
      }
    } catch (error) {
      console.error('Error processing form data:', error);
    }
    
    return processedData;
  }

  createEntity(formData: any): void {
    this.restService.createEntity(this.entityType, formData).subscribe({
      next: (response) => {
        this.submitting = false;
        // For now, just go back to the entity list to avoid navigation issues
        this.router.navigate(['/entity', this.entityType]);
      },
      error: (err) => {
        console.error('Error creating entity:', err);
        this.error = 'Failed to create entity. Please check your data and try again.';
        this.submitting = false;
      }
    });
  }

  updateEntity(formData: any): void {
    this.restService.updateEntity(this.entityType, this.entityId, formData).subscribe({
      next: (response) => {
        this.submitting = false;
        // For now, just go back to the entity list to avoid navigation issues
        this.router.navigate(['/entity', this.entityType]);
      },
      error: (err) => {
        console.error('Error updating entity:', err);
        this.error = 'Failed to update entity. Please check your data and try again.';
        this.submitting = false;
      }
    });
  }

  goBack(): void {
    if (this.isEditMode() && this.entityId) {
      this.router.navigate(['/entity', this.entityType, this.entityId]);
    } else {
      this.router.navigate(['/entity', this.entityType]);
    }
  }
  
  goToEdit(): void {
    if (this.entityId) {
      this.router.navigate(['/entity', this.entityType, this.entityId, 'edit']);
    }
  }
  
}

// sveltekit/src/lib/components/EntityForm.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { metadata } from '../stores/metadata.js';
  import { rest } from '../stores/rest.js';
  import { notifications } from '../stores/notifications.js';
  import { operationResult } from '../stores/operationResult.js';
  import type { Entity, ValidationFailure, ViewMode } from '../types.js';
  import OperationResultBanner from './OperationResultBanner.svelte';
  import currency from 'currency.js';

  export let entityType: string;
  export let entityId: string = '';
  export let mode: ViewMode = 'details';

  let entity: Entity | null = null;
  let formData: Record<string, any> = {};
  let displayFields: string[] = [];
  let submitting = false;
  let error = '';
  let validationErrors: ValidationFailure[] = [];

  // Operation result banner state
  let operationMessage: string | null = null;
  let operationType: 'success' | 'error' | 'warning' | 'info' = 'success';

  // Entity selector state
  let showEntitySelector = false;
  let entitySelectorEntities: Entity[] = [];
  let entitySelectorType = '';
  let currentFieldName = '';

  $: isDetailsMode = mode === 'details';
  $: isEditMode = mode === 'edit';
  $: isCreateMode = mode === 'create';

  $: {
    if (entityType) {
      setupForm();
      checkForOperationResult();
    }
  }

  async function setupForm() {
    try {
      // Get display fields for this mode
      const entityMetadata = metadata.getEntityMetadata(entityType);
      displayFields = metadata.getViewFields(entityMetadata, mode);

      if (isCreateMode) {
        // Create mode - start with empty form
        entity = { id: '' };
        initializeFormData();
      } else if (entityId) {
        // Edit or details mode - load entity data
        const response = await rest.getEntity(entityType, entityId, mode);
        entity = response.data;
        
        if (entity) {
          initializeFormData();
          
          // Handle validation errors from server response
          if (response.notifications) {
            validationErrors = extractValidationErrors(response);
          }
        } else {
          error = 'No entity data returned from the server.';
        }
      }
    } catch (err: any) {
      console.error('Error setting up form:', err);
      error = 'Failed to load entity data.';
    }
  }

  function initializeFormData() {
    if (!entity) return;
    
    formData = {};
    displayFields.forEach(fieldName => {
      const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
      let value = entity![fieldName];

      // Handle different field types
      if (fieldMeta?.type === 'Boolean') {
        formData[fieldName] = Boolean(value);
      } else if (fieldMeta?.type === 'Currency' && value != null) {
        formData[fieldName] = currency(value).format();
      } else {
        formData[fieldName] = value || '';
      }
    });
  }

  function extractValidationErrors(response: any): ValidationFailure[] {
    // Convert API response to validation failures
    // This would need to match your Angular validation service logic
    return [];
  }

  function checkForOperationResult() {
    const result = operationResult.getOperationResultForEntity(entityType);
    if (result) {
      operationMessage = result.message;
      operationType = result.type;
      operationResult.clearOperationResult();
    }
  }

  function onBannerDismissed() {
    operationMessage = null;
  }

  function getFieldDisplayName(fieldName: string): string {
    if (fieldName === 'id') return 'ID';
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    return fieldMeta?.ui?.displayName || fieldName;
  }

  function isFieldRequired(fieldName: string): boolean {
    if (fieldName === 'id') return true;
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    if (!fieldMeta) return false;
    if (fieldMeta.type === 'Boolean') return false;
    return fieldMeta.required || false;
  }

  function isFieldReadOnly(fieldName: string): boolean {
    if (isDetailsMode) return true;
    if (fieldName === 'id') return true;
    
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    if (!fieldMeta) return false;
    
    return fieldMeta.ui?.readOnly || 
           fieldMeta.autoGenerate || 
           fieldMeta.autoUpdate ||
           !fieldMeta.client_edit;
  }

  function getFieldOptions(fieldName: string): string[] {
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    if (!fieldMeta || !fieldMeta.enum || !fieldMeta.enum.values) return [];
    return fieldMeta.enum.values;
  }

  function shouldShowSpinner(fieldName: string): boolean {
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    const spinnerStep = fieldMeta?.ui?.spinnerStep;
    return spinnerStep !== undefined && spinnerStep !== 0;
  }

  function getSpinnerStep(fieldName: string): number {
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    return fieldMeta?.ui?.spinnerStep || 1;
  }

  function getInputType(fieldName: string): string {
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    if (!fieldMeta) return 'text';

    switch (fieldMeta.type) {
      case 'Number':
      case 'Currency':
        return 'number';
      case 'Date':
        return 'date';
      case 'Email':
        return 'email';
      case 'Password':
        return 'password';
      default:
        return 'text';
    }
  }

  async function onSubmit(event: Event) {
    event.preventDefault();
    
    if (isDetailsMode) {
      // Navigate to edit mode
      goto(`/entity/${entityType}/${entityId}/edit`);
      return;
    }

    submitting = true;
    error = '';
    validationErrors = [];
    notifications.clear();

    try {
      const submitData = prepareFormData();
      
      if (isEditMode) {
        await rest.updateEntity(entityType, entityId, submitData);
      } else if (isCreateMode) {
        await rest.createEntity(entityType, submitData);
      }

      // Success - set operation result and navigate
      const operation = isCreateMode ? 'created' : 'updated';
      const message = `${entityType} was successfully ${operation}.`;
      operationResult.setOperationResult(message, 'success', entityType);
      
      goto(`/entity/${entityType}`);
    } catch (err: any) {
      handleApiError(err);
    } finally {
      submitting = false;
    }
  }

  function prepareFormData(): Record<string, any> {
    const submitData: Record<string, any> = {};
    
    Object.keys(formData).forEach(fieldName => {
      const value = formData[fieldName];
      const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
      
      // Boolean fields: always include
      if (fieldMeta?.type === 'Boolean') {
        submitData[fieldName] = Boolean(value);
      }
      // Other fields: include non-empty values
      else if (value !== null && value !== undefined && value !== '') {
        // Convert currency fields to numbers
        if (fieldMeta?.type === 'Currency' && typeof value === 'string') {
          try {
            const currencyValue = currency(value);
            submitData[fieldName] = currencyValue.value;
          } catch (error) {
            console.warn(`Failed to parse currency value for ${fieldName}:`, value, error);
            submitData[fieldName] = value;
          }
        } else {
          submitData[fieldName] = value;
        }
      }
    });
    
    return submitData;
  }

  function handleApiError(err: any) {
    notifications.clear();
    console.log('API Error:', err);
    
    let errorMessage = 'An error occurred while processing your request.';
    
    if (err.error?.message) {
      errorMessage = err.error.message;
    } else if (err.message) {
      errorMessage = err.message;
    } else if (err.status === 422) {
      errorMessage = 'Validation errors occurred. Please check the form fields below.';
    } else if (err.status === 500) {
      errorMessage = 'Server error occurred. Please try again or contact support.';
    } else if (err.status === 0 || err.name === 'HttpErrorResponse') {
      errorMessage = 'Network error. Please check your connection and try again.';
    }
    
    notifications.showError(errorMessage);
  }

  function goBack() {
    goto(`/entity/${entityType}`);
  }

  function openObjectIdField(fieldName: string) {
    if (!fieldName.endsWith('Id')) {
      return;
    }
    
    const relatedEntityType = fieldName.substring(0, fieldName.length - 2);
    
    if (isEditMode || isCreateMode) {
      showIdSelector(fieldName, relatedEntityType);
      return;
    }
    
    // In view mode, navigate to the related entity
    const objectIdValue = entity?.[fieldName];
    if (objectIdValue) {
      goto(`/entity/${relatedEntityType}/${objectIdValue}`);
    }
  }

  async function showIdSelector(fieldName: string, relatedEntityType: string) {
    try {
      const entities = await rest.getEntityList(relatedEntityType, mode);
      entitySelectorEntities = entities;
      entitySelectorType = relatedEntityType;
      currentFieldName = fieldName;
      showEntitySelector = true;
    } catch (err: any) {
      console.error('Error fetching entities for selector:', err);
      notifications.showError('Failed to load entities for selection');
    }
  }

  function onEntitySelected(selectedEntity: Entity) {
    if (!selectedEntity || !currentFieldName) return;
    
    formData[currentFieldName] = selectedEntity.id;
    showEntitySelector = false;
  }

  function onEntitySelectorClosed() {
    showEntitySelector = false;
  }

  onMount(() => {
    setupForm();
  });
</script>

<div class="container">
  <h2>
    {#if isCreateMode}
      Create {metadata.getTitle(entityType)}
    {:else if isEditMode}
      Edit {metadata.getTitle(entityType)}
    {:else}
      {metadata.getTitle(entityType)} Details
    {/if}
  </h2>

  <!-- Operation Result Banner -->
  {#if operationMessage}
    <OperationResultBanner
      message={operationMessage}
      type={operationType}
      on:dismissed={onBannerDismissed}
    />
  {/if}

  {#if error}
    <div class="alert alert-danger">
      {error}
    </div>
  {/if}

  <form on:submit={onSubmit}>
    {#each displayFields as fieldName}
      {@const fieldMeta = metadata.getFieldMetadata(entityType, fieldName)}
      {@const isReadOnly = isFieldReadOnly(fieldName)}
      {@const options = getFieldOptions(fieldName)}
      
      <div class="mb-3">
        <label for={fieldName} class="form-label">
          {getFieldDisplayName(fieldName)}
          {#if isFieldRequired(fieldName)}
            <span class="text-danger">*</span>
          {/if}
        </label>

        {#if fieldMeta?.type === 'Boolean'}
          <div class="form-check">
            <input
              type="checkbox"
              id={fieldName}
              class="form-check-input"
              bind:checked={formData[fieldName]}
              disabled={isReadOnly}
            />
          </div>
        {:else if options.length > 0}
          <select
            id={fieldName}
            class="form-select"
            bind:value={formData[fieldName]}
            disabled={isReadOnly}
          >
            <option value="">Select...</option>
            {#each options as option}
              <option value={option}>{option}</option>
            {/each}
          </select>
        {:else if fieldMeta?.type === 'ObjectId'}
          <div class="input-group">
            <input
              type="text"
              id={fieldName}
              class="form-control"
              bind:value={formData[fieldName]}
              readonly={isReadOnly}
            />
            {#if !isReadOnly}
              <button
                type="button"
                class="btn btn-outline-secondary"
                on:click={() => openObjectIdField(fieldName)}
              >
                Select
              </button>
            {:else}
              <button
                type="button"
                class="btn btn-outline-primary"
                on:click={() => openObjectIdField(fieldName)}
              >
                View
              </button>
            {/if}
          </div>
        {:else if fieldMeta?.type === 'Number' || fieldMeta?.type === 'Currency'}
          <input
            type="number"
            id={fieldName}
            class="form-control {shouldShowSpinner(fieldName) ? 'show-spinner' : ''}"
            bind:value={formData[fieldName]}
            readonly={isReadOnly}
            step={shouldShowSpinner(fieldName) ? getSpinnerStep(fieldName) : undefined}
          />
        {:else if fieldMeta?.type === 'Date'}
          <input
            type="date"
            id={fieldName}
            class="form-control"
            bind:value={formData[fieldName]}
            readonly={isReadOnly}
          />
        {:else if fieldMeta?.type === 'Email'}
          <input
            type="email"
            id={fieldName}
            class="form-control"
            bind:value={formData[fieldName]}
            readonly={isReadOnly}
          />
        {:else if fieldMeta?.type === 'Password'}
          <input
            type="password"
            id={fieldName}
            class="form-control"
            bind:value={formData[fieldName]}
            readonly={isReadOnly}
          />
        {:else}
          <input
            type="text"
            id={fieldName}
            class="form-control"
            bind:value={formData[fieldName]}
            readonly={isReadOnly}
          />
        {/if}
      </div>
    {/each}

    <div class="d-flex gap-2">
      <button type="button" class="btn btn-secondary" on:click={goBack}>
        Back
      </button>
      
      {#if !isDetailsMode}
        <button type="submit" class="btn btn-primary" disabled={submitting}>
          {#if submitting}
            Submitting...
          {:else if isCreateMode}
            Create
          {:else}
            Update
          {/if}
        </button>
      {:else}
        <button type="submit" class="btn btn-primary">
          Edit
        </button>
      {/if}
    </div>
  </form>
</div>

<!-- Entity Selector Modal -->
{#if showEntitySelector}
  <div class="modal-backdrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Select {entitySelectorType}</h5>
          <button type="button" class="btn-close" on:click={onEntitySelectorClosed}></button>
        </div>
        <div class="modal-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>ID</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {#each entitySelectorEntities as selectorEntity}
                <tr>
                  <td>{selectorEntity.id}</td>
                  <td>
                    <button
                      type="button"
                      class="btn btn-primary btn-sm"
                      on:click={() => onEntitySelected(selectorEntity)}
                    >
                      Select
                    </button>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" on:click={onEntitySelectorClosed}>
            Close
          </button>
        </div>
      </div>
    </div>
  </div>
{/if}

<style>
  .container {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
  }

  .form-label {
    font-weight: 600;
    margin-bottom: 0.5rem;
  }

  .form-control,
  .form-select {
    display: block;
    width: 100%;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    background-color: #fff;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
  }

  .form-control:focus,
  .form-select:focus {
    border-color: #86b7fe;
    outline: 0;
    box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
  }

  .form-control:disabled,
  .form-select:disabled {
    background-color: #e9ecef;
    opacity: 1;
  }

  .form-check {
    min-height: 1.5rem;
    padding-left: 1.5em;
  }

  .form-check-input {
    width: 1em;
    height: 1em;
    margin-top: 0.25em;
    margin-left: -1.5em;
  }

  .input-group {
    position: relative;
    display: flex;
    flex-wrap: wrap;
    align-items: stretch;
    width: 100%;
  }

  .input-group .form-control {
    position: relative;
    flex: 1 1 auto;
    width: 1%;
    min-width: 0;
  }

  .input-group .btn {
    position: relative;
    z-index: 2;
  }

  .btn {
    display: inline-block;
    font-weight: 400;
    line-height: 1.5;
    text-align: center;
    text-decoration: none;
    vertical-align: middle;
    cursor: pointer;
    border: 1px solid transparent;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    border-radius: 0.25rem;
    transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out;
  }

  .btn-primary {
    color: #fff;
    background-color: #0d6efd;
    border-color: #0d6efd;
  }

  .btn-primary:hover {
    background-color: #0b5ed7;
    border-color: #0a58ca;
  }

  .btn-secondary {
    color: #fff;
    background-color: #6c757d;
    border-color: #6c757d;
  }

  .btn-secondary:hover {
    background-color: #5c636a;
    border-color: #565e64;
  }

  .btn-outline-secondary {
    color: #6c757d;
    border-color: #6c757d;
  }

  .btn-outline-secondary:hover {
    color: #fff;
    background-color: #6c757d;
    border-color: #6c757d;
  }

  .btn-outline-primary {
    color: #0d6efd;
    border-color: #0d6efd;
  }

  .btn-outline-primary:hover {
    color: #fff;
    background-color: #0d6efd;
    border-color: #0d6efd;
  }

  .btn:disabled {
    opacity: 0.65;
    cursor: not-allowed;
  }

  .btn-sm {
    padding: 0.25rem 0.5rem;
    font-size: 0.875rem;
    border-radius: 0.2rem;
  }

  .d-flex {
    display: flex;
  }

  .gap-2 {
    gap: 0.5rem;
  }

  .mb-3 {
    margin-bottom: 1rem;
  }

  .alert {
    padding: 0.75rem 1.25rem;
    margin-bottom: 1rem;
    border: 1px solid transparent;
    border-radius: 0.25rem;
  }

  .alert-danger {
    color: #721c24;
    background-color: #f8d7da;
    border-color: #f5c6cb;
  }

  .text-danger {
    color: #dc3545;
  }

  /* Modal styles */
  .modal-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1050;
  }

  .modal-dialog {
    max-width: 500px;
    width: 90%;
    margin: 1.75rem auto;
  }

  .modal-content {
    background-color: #fff;
    border: 1px solid rgba(0, 0, 0, 0.2);
    border-radius: 0.3rem;
    box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
  }

  .modal-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem;
    border-bottom: 1px solid #dee2e6;
  }

  .modal-title {
    margin: 0;
    font-size: 1.25rem;
    font-weight: 500;
  }

  .modal-body {
    padding: 1rem;
    max-height: 400px;
    overflow-y: auto;
  }

  .modal-footer {
    display: flex;
    justify-content: flex-end;
    padding: 1rem;
    border-top: 1px solid #dee2e6;
  }

  .btn-close {
    background: transparent;
    border: 0;
    font-size: 1.125rem;
    font-weight: 700;
    line-height: 1;
    color: #000;
    text-shadow: 0 1px 0 #fff;
    opacity: 0.5;
    cursor: pointer;
  }

  .btn-close:hover {
    opacity: 0.75;
  }

  .btn-close::before {
    content: "×";
  }

  .table {
    width: 100%;
    margin-bottom: 1rem;
    border-collapse: collapse;
  }

  .table th,
  .table td {
    padding: 0.75rem;
    vertical-align: top;
    border-top: 1px solid #dee2e6;
  }

  .table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
    border-top: 0;
  }

  .table-striped tbody tr:nth-of-type(odd) {
    background-color: rgba(0, 0, 0, 0.05);
  }

  /* Hide spinners by default */
  input::-webkit-outer-spin-button,
  input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }
  
  input[type=number] {
    -moz-appearance: textfield;
  }

  /* Show spinners only when the class is present */
  .show-spinner::-webkit-outer-spin-button,
  .show-spinner::-webkit-inner-spin-button {
    -webkit-appearance: inner-spin-button;
    margin: 0;
  }
  
  .show-spinner {
    -moz-appearance: spinner-textfield;
  }
</style>
