// ui/src/app/components/entity-list.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MetadataService } from '../services/metadata.service';
import { EntityService } from '../services/entity.service';
import { ConfigService } from '../services/config.service';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { RestService } from '../services/rest.service';
import { ModeService, SUMMARY } from '../services/mode.service';
import { forkJoin, of } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { NotificationService } from '../services/notification.service';
import { ValidationService } from '../services/validation.service';
import { RefreshService } from '../services/refresh.service';
import { Subscription } from 'rxjs';
import { OperationResultBannerComponent, OperationResultType } from './operation-result-banner.component';
import { OperationResultService } from '../services/operation-result.service';

@Component({
  selector: 'app-entity-list',
  standalone: true,
  imports: [CommonModule, OperationResultBannerComponent],
  styleUrls: ['../common.css'],
  template: `
    <div class="mt-4">
      <h2>{{ metadataService.getTitle(entityType) }}</h2>
      
      <!-- Operation Result Banner -->
      <operation-result-banner
        [message]="operationMessage"
        [type]="operationType"
        (dismissed)="onBannerDismissed()">
      </operation-result-banner>
      
      <!-- Create button - checks both metadata operations and auth permissions -->
      <div *ngIf="entityService.canCreate(entityType)">
        <div class="mb-3">
          <button class="btn btn-entity-create" (click)="this.entityService.navigateToCreate(entityType)">Create {{ entityType }}</button>
        </div>
      </div>
      
      <div *ngIf="loading" class="text-center">
        <p>Loading...</p>
      </div>
      
      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>
      
      <div *ngIf="!loading && !error">
        <!-- Check if there are any entities to display -->
        <div *ngIf="data.length === 0" class="alert alert-info">
          No {{ entityType }} records found.
        </div>
        
        <!-- Table layout with one row per entity -->
        <div *ngIf="data.length > 0" class="custom-table-container">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th *ngFor="let field of displayFields">{{ entityService.getFieldDisplayName(entityType, field) }}</th>
                <th class="actions-column">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let row of data">
                <td *ngFor="let field of displayFields" [innerHTML]="row._formattedValues?.[field] | async"></td>
                <td class="actions-column text-nowrap">
                  <div class="btn-group btn-group-sm">
                    <!-- Consistent button order: View, Edit, Create, Delete -->
                    <button *ngIf="entityService.canRead(entityType)"
                      class="btn btn-entity-details me-1"
                      (click)="this.entityService.viewEntity(entityType, row['id'])">Details</button>
                    <button *ngIf="entityService.canUpdate(entityType)"
                      class="btn btn-entity-edit me-1"
                      (click)="this.entityService.editEntity(entityType, row['id'])">Edit</button>
                    <!-- Create not shown for individual rows since it applies to the entity type, not a specific row -->
                    <button *ngIf="entityService.canDelete(entityType)"
                      class="btn btn-entity-delete"
                      (click)="this.restService.deleteEntity(entityType, row['id'])">Delete</button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .container-fluid { 
      padding-left: 10px;
      padding-right: 10px;
    }
    
    /* Make table fill available space */
    .table-responsive {
      width: 100%;
      overflow-x: auto;
      margin-bottom: 20px; /* Add space below table */
      padding-bottom: 5px; /* Ensure bottom of table is visible */
    }
    
    /* Use auto table layout for more natural column sizing */
    .table {
      table-layout: auto;
    }
    
    /* Fix action buttons visibility */
    .btn-group {
      white-space: nowrap;
      display: flex;
    }
    
    /* Ensure text truncation starts at beginning, not end */
    td {
      max-width: 300px; /* Larger max-width for data cells */
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      /* direction: rtl;  /* Right-to-left to truncate start of text */
      text-align: left; /* Keep text aligned left */
    }
    
    /* Actions column should not truncate and should have enough space */
    .actions-column {
      direction: ltr;
      white-space: nowrap;
      width: 200px !important; /* Force minimum width with !important */
      min-width: 200px !important;
      padding-right: 15px !important; /* Add some extra padding */
    }
    
    /* Ensure headers match cell widths */
    th {
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    
    /* Tighten up table row heights */
    .table td,
    .table th {
      padding-top: 0.25rem;
      padding-bottom: 0.25rem;
      vertical-align: middle;
    }
  `]
})
export class EntityListComponent implements OnInit, OnDestroy {
  entityType: string = '';
  data: any[] = []
  displayFields: string[] = [];
  loading: boolean = true;
  error: string = '';
  totalCount: number = 0;
  
  // Store operation permissions for row-level actions
  canRead: boolean = false;
  canUpdate: boolean = false;
  canDelete: boolean = false;
  
  // Refresh subscription
  private refreshSubscription: Subscription | null = null;
  
  // Operation result banner state
  operationMessage: string | null = null;
  operationType: OperationResultType = 'success';

  constructor(
    public metadataService: MetadataService,
    public entityService: EntityService,
    private route: ActivatedRoute,
    public restService: RestService,
    private modeService: ModeService,
    private sanitizer: DomSanitizer,
    private notificationService: NotificationService,
    private validationService: ValidationService,
    private refreshService: RefreshService,
    private operationResultService: OperationResultService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.entityType = params['entityType'];
      
      // Clean up previous refresh subscription
      if (this.refreshSubscription) {
        this.refreshSubscription.unsubscribe();
      }
      
      // Subscribe to refresh events for this entity type
      this.refreshSubscription = this.refreshService.getRefreshObservable(this.entityType).subscribe(() => {
        console.log(`EntityListComponent: Refresh triggered for ${this.entityType}`);
        this.loadEntities();
      });
      
      // Check for operation results when navigating to this entity type
      this.checkForOperationResult();
      
      // Load entities
      this.loadEntities();
    });
  }
  
  loadEntities(): void {
    this.loading = true;
    this.error = '';
    
    // Wait for entities to be loaded
    this.displayFields = this.entityService.getViewFields(this.entityType, SUMMARY);
        
    // Use RestService instead of HttpClient directly  
    this.restService.getEntityList(this.entityType, 'summary').subscribe({
      next: (response: any) => {
        // Handle new response format with metadata
        const entities = response.data || response; // Fallback for old format
        this.totalCount = response.metadata?.total || entities.length; // Extract count
        
        // Update the entity service with the current record count
        this.entityService.setRecordCount(this.totalCount);
        
        // Process each entity using embedded FK data from server response
        this.data = entities.map((entity: any) => {
          const processedEntity: any = { ...entity, _formattedValues: {} };

          this.displayFields.forEach(field => {
            const metadata = this.metadataService.getFieldMetadata(this.entityType, field);
            const rawValue = entity[field];

            // Check if it's an ObjectId field with a show configuration for the current mode (SUMMARY)
            const showConfig = metadata?.ui?.show ? this.metadataService.getShowConfig(this.entityType, field, SUMMARY) : null;

            if (metadata?.type === 'ObjectId' && showConfig) {
              // Use embedded FK data instead of making individual REST calls
              const formattedValue = this.entityService.formatObjectIdValueWithEmbeddedData(
                this.entityType, field, SUMMARY, rawValue, entity, showConfig
              );
              processedEntity._formattedValues[field] = of(this.sanitizer.bypassSecurityTrustHtml(formattedValue));
            } else {
              // For other field types or ObjectId without show config, use the synchronous formatter
              const formattedValue = this.entityService.formatFieldValue(this.entityType, field, SUMMARY, rawValue);
              processedEntity._formattedValues[field] = of(this.sanitizer.bypassSecurityTrustHtml(formattedValue));
            }
          });

          return processedEntity;
        });
            
        this.loading = false;
      },
      error: (err) => {
        console.error('Error loading entities:', err);
        this.error = 'Failed to load entities';
        this.loading = false;
      }
    });
  }
  
  // Custom actions are not currently implemented in the stateless approach
  // getCustomActions(entity: Entity): { key: string, label: string, icon?: string }[] {
  //   // Will be implemented when hooks are added back
  //   return [];
  // }
  
  // executeCustomAction(actionKey: string, entity: Entity): void {
  //   // Will be implemented when hooks are added back
  //   console.log(`Custom action ${actionKey} would be executed on entity:`, entity);
  // }

  ngOnDestroy(): void {
    // Clean up refresh subscription
    if (this.refreshSubscription) {
      this.refreshSubscription.unsubscribe();
    }
  }
  
  /**
   * Check for pending operation results for this entity type
   */
  private checkForOperationResult(): void {
    const result = this.operationResultService.getOperationResultForEntity(this.entityType);
    if (result) {
      this.operationMessage = result.message;
      this.operationType = result.type;
      // Clear the result from the service since we're now displaying it
      this.operationResultService.clearOperationResult();
    }
  }
  
  /**
   * Handle dismissing the operation result banner
   */
  onBannerDismissed(): void {
    this.operationMessage = null;
  }
  
}

// sveltekit/src/lib/components/EntityList.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { metadata } from '../stores/metadata.js';
  import { rest } from '../stores/rest.js';
  import { operationResult } from '../stores/operationResult.js';
  import type { Entity } from '../types.js';
  import OperationResultBanner from './OperationResultBanner.svelte';

  export let entityType: string;

  let entities: Entity[] = [];
  let displayFields: string[] = [];
  let loading = true;
  let error = '';
  let totalCount = 0;

  // Operation result banner state
  let operationMessage: string | null = null;
  let operationType: 'success' | 'error' | 'warning' | 'info' = 'success';

  $: {
    if (entityType) {
      loadEntities();
      checkForOperationResult();
    }
  }

  async function loadEntities() {
    loading = true;
    error = '';

    try {
      // Get display fields for summary mode
      const entityMetadata = metadata.getEntityMetadata(entityType);
      displayFields = metadata.getViewFields(entityMetadata, 'summary');

      // Load entities
      const response = await rest.getEntityList(entityType, 'summary');
      entities = response;
      totalCount = response.length; // Simple count for now
      loading = false;
    } catch (err: any) {
      console.error('Error loading entities:', err);
      error = 'Failed to load entities';
      loading = false;
    }
  }

  function checkForOperationResult() {
    const result = operationResult.getOperationResultForEntity(entityType);
    if (result) {
      operationMessage = result.message;
      operationType = result.type;
      operationResult.clearOperationResult();
    }
  }

  function onBannerDismissed() {
    operationMessage = null;
  }

  function navigateToCreate() {
    goto(`/entity/${entityType}/create`);
  }

  function navigateToDetails(id: string) {
    goto(`/entity/${entityType}/${id}`);
  }

  function navigateToEdit(id: string) {
    goto(`/entity/${entityType}/${id}/edit`);
  }

  async function deleteEntity(id: string) {
    try {
      await rest.deleteEntity(entityType, id);
      // Reload the list after successful delete
      await loadEntities();
    } catch (err) {
      console.error('Delete failed:', err);
    }
  }

  function getFieldDisplayName(fieldName: string): string {
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    return fieldMeta?.ui?.displayName || fieldName;
  }

  function formatFieldValue(entity: Entity, fieldName: string): string {
    const value = entity[fieldName];
    if (value === null || value === undefined) return '';
    
    const fieldMeta = metadata.getFieldMetadata(entityType, fieldName);
    
    // Handle different field types
    if (fieldMeta?.type === 'Currency') {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD'
      }).format(Number(value) || 0);
    }
    
    if (fieldMeta?.type === 'Date') {
      return new Date(value).toLocaleDateString();
    }
    
    if (fieldMeta?.type === 'Boolean') {
      return value ? 'Yes' : 'No';
    }

    // For ObjectId fields, check if we have embedded FK data
    if (fieldMeta?.type === 'ObjectId') {
      const showConfig = metadata.getShowConfig(entityType, fieldName, 'summary');
      if (showConfig && entity[showConfig.endpoint]) {
        const relatedEntity = entity[showConfig.endpoint];
        const displayFields = showConfig.displayInfo[0].fields;
        return displayFields.map(field => relatedEntity[field]).join(' - ');
      }
    }
    
    return String(value);
  }

  function canCreate(): boolean {
    return metadata.isValidOperation(entityType, 'c');
  }

  function canRead(): boolean {
    return metadata.isValidOperation(entityType, 'r');
  }

  function canUpdate(): boolean {
    return metadata.isValidOperation(entityType, 'u');
  }

  function canDelete(): boolean {
    return metadata.isValidOperation(entityType, 'd');
  }

  onMount(() => {
    loadEntities();
  });
</script>

<div class="mt-4">
  <h2>{metadata.getTitle(entityType)}</h2>
  
  <!-- Operation Result Banner -->
  {#if operationMessage}
    <OperationResultBanner
      message={operationMessage}
      type={operationType}
      on:dismissed={onBannerDismissed}
    />
  {/if}
  
  <!-- Create button -->
  {#if canCreate()}
    <div class="mb-3">
      <button class="btn btn-entity-create" on:click={navigateToCreate}>
        Create {entityType}
      </button>
    </div>
  {/if}
  
  {#if loading}
    <div class="text-center">
      <p>Loading...</p>
    </div>
  {:else if error}
    <div class="alert alert-danger">
      {error}
    </div>
  {:else}
    {#if entities.length === 0}
      <div class="alert alert-info">
        No {entityType} records found.
      </div>
    {:else}
      <!-- Table layout -->
      <div class="custom-table-container">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              {#each displayFields as field}
                <th>{getFieldDisplayName(field)}</th>
              {/each}
              <th class="actions-column">Actions</th>
            </tr>
          </thead>
          <tbody>
            {#each entities as entity}
              <tr>
                {#each displayFields as field}
                  <td>{formatFieldValue(entity, field)}</td>
                {/each}
                <td class="actions-column text-nowrap">
                  <div class="btn-group btn-group-sm">
                    {#if canRead()}
                      <button
                        class="btn btn-entity-details me-1"
                        on:click={() => navigateToDetails(entity.id)}
                      >
                        Details
                      </button>
                    {/if}
                    {#if canUpdate()}
                      <button
                        class="btn btn-entity-edit me-1"
                        on:click={() => navigateToEdit(entity.id)}
                      >
                        Edit
                      </button>
                    {/if}
                    {#if canDelete()}
                      <button
                        class="btn btn-entity-delete"
                        on:click={() => deleteEntity(entity.id)}
                      >
                        Delete
                      </button>
                    {/if}
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    {/if}
  {/if}
</div>

<style>
  .container-fluid { 
    padding-left: 10px;
    padding-right: 10px;
  }
  
  .table-responsive {
    width: 100%;
    overflow-x: auto;
    margin-bottom: 20px;
    padding-bottom: 5px;
  }
  
  .table {
    table-layout: auto;
  }
  
  .btn-group {
    white-space: nowrap;
    display: flex;
  }
  
  td {
    max-width: 300px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    text-align: left;
  }
  
  .actions-column {
    white-space: nowrap;
    width: 200px !important;
    min-width: 200px !important;
    padding-right: 15px !important;
  }
  
  th {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  
  .table td,
  .table th {
    padding-top: 0.25rem;
    padding-bottom: 0.25rem;
    vertical-align: middle;
  }

  /* Button styles - matching Angular UI */
  .btn {
    padding: 0.25rem 0.5rem;
    font-size: 0.875rem;
    border-radius: 0.25rem;
    text-decoration: none;
    cursor: pointer;
    border: 1px solid transparent;
  }

  .btn-entity-create {
    background-color: #198754;
    border-color: #198754;
    color: white;
  }

  .btn-entity-details {
    background-color: #0d6efd;
    border-color: #0d6efd;
    color: white;
  }

  .btn-entity-edit {
    background-color: #fd7e14;
    border-color: #fd7e14;
    color: white;
  }

  .btn-entity-delete {
    background-color: #dc3545;
    border-color: #dc3545;
    color: white;
  }

  .btn:hover {
    opacity: 0.85;
  }

  .btn-group-sm .btn {
    font-size: 0.75rem;
    padding: 0.125rem 0.25rem;
  }

  .me-1 {
    margin-right: 0.25rem;
  }

  .alert {
    padding: 0.75rem 1.25rem;
    margin-bottom: 1rem;
    border: 1px solid transparent;
    border-radius: 0.25rem;
  }

  .alert-danger {
    color: #721c24;
    background-color: #f8d7da;
    border-color: #f5c6cb;
  }

  .alert-info {
    color: #0c5460;
    background-color: #d1ecf1;
    border-color: #bee5eb;
  }

  .text-center {
    text-align: center;
  }

  .text-nowrap {
    white-space: nowrap;
  }

  .mb-3 {
    margin-bottom: 1rem;
  }

  .mt-4 {
    margin-top: 1.5rem;
  }
</style>
